### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by AltQuest**
Emerald updates

currencycomand added with flags in bitquest to update scoreboard on currencies

pvp added on per plot

nether buildable and buyable @ 4X land prices

### CODE REVIEW

**Comment by AltQuest** [comment]
added [MOD] to player display if mod also updated to work with clan displays

also EXPLODI please look at the nether, emerald, and pvp updates too please!

**Comment by Jorropo** [comment]
Your commit name really need to be better.

**Comment by AltQuest** [comment]
How so?

**Comment by Jorropo** [comment]
Explain what you do in this commit eg:
```Adding /example command.```
or
```Fix an example bug.```

**Comment by AltQuest** [comment]
Like this? Better? I'm still learning github... 
https://github.com/AltQuest/bitquest/commit/5befca79b25aee6d7867b06e4626115449684f21

**Pull request merged**
