### PR TITLE
Add word filter for chat

### PR DESCRIPTION
**Pull request by juanj**
Add a filter for chat words. #96 
Each player can decide which words to filter with the command
`/filter <add|remove> <word to filter> [optional word to replace with]`

The default replaced word is the same word in asterisks.

### CODE REVIEW

**Comment by juanj** [comment]
Right now there is no way to filter sentences because parameters are split by spaces.
I'm thinking that this can be solved by interpreting other character as space.
Something like `this_is_a_sentence = this is a sentence`

**Comment by CubeFromSpace** [comment]
This is a great idea :)

**Comment by CubeFromSpace** [comment]
Maybe you should develop this as a plugin. You can profit from that🙂

**Comment by juanj** [comment]
This PR is kinda out of the scope.
Is fun, but we need a ignore/mute command.

**Pull request closed without merging**
