### PR TITLE
add level 100 pigmen (far into nether)

### PR DESCRIPTION
**Pull request by Shiny-andKittens**
Would make the Nether and End safer, but make loot lesser. Created in preparation of the end.
Once again, will need checked for errors, and may not be necessary.

### CODE REVIEW

**Comment by AndrewBuck** [comment]
This looks good to me.  I think it is a good idea to have weaker mobs near the spawn centers, and it makes sense to extend this to the nether and end as well.  Especially since it would be nice to allow low level players to make use of the nether roads, at least out to some reasonable distance, before they run into higher level mobs.

**Comment by Burntuno** [comment]
Nether needs harder mobs... maybe level 100.

**Comment by Burntuno** [comment]
Bitquest has to have challenge... Take overworld rails of you can't make it through Nether.

**Comment by theraccoonbear** [comment]
@Shiny-andKittens I didn't look too closely at it.  The only feedback I have would be consistency in indentation (tabs v. spaces), but that's already a problem in this codebase.  An `.editorconfig` would probably be worth adding.

**Comment by Shiny-andKittens** [comment]
@theraccoonbear what it did was increase nerf level 1.5x for Nether, and 2x for End

**Comment by Shiny-andKittens** [comment]
This feature was suggested by @Burntuno on Slack

**Comment by Xeyler** [comment]
I'm not sure that the nether technically has a spawn point... I'll look into this.

Also, after a quick look at the current code, it seems like some cleaning may be required to make it more readable. I'll work something out.

**Comment by Shiny-andKittens** [comment]
@xeyler all the code needs cleaned up, if this is merged or rejected, then I will make a PR to do so.

**Comment by Shiny-andKittens** [comment]
I will remove the nerfing, upon request of @Burntuno

**Comment by Shiny-andKittens** [comment]
I have unintentionally ruined this, gonna redo it again.

**Comment by QuintLeo** [comment]
Nether technically does not have a spawn point - if you die there you respawn in the Overworld.
Locations however do correspond to Overworld locations, at a 1:8 ratio - travel 100 blocks in the Nether equals 800 blocks in the Overworld if you have portals that correspond.

**Pull request closed without merging**
