### PR TITLE
Add as many users as wanted to a claim

### PR DESCRIPTION
**Pull request by lunears**
Usage: `*addusername*` on a sign
New pull request because I wasn't adding the array of builders to REDIS.
**Needs Testing**

### CODE REVIEW

**Comment by DiamondCardz** [comment]
line 171 is missing a semi-colon at the end

**Comment by lunears** [comment]
Fixed, I also made the array for builders be created on the creation of a claim.

**Comment by PsiLupan** [comment]
1. You're initializing multiple claimusers objects that you aren't even using, such as in areaForLocation.
2. canBuild is using bitQuest, which isn't necessary since you're in the class you'd be accessing statically. Plus the variable doesn't exist for that reason, so this wouldn't even compile.
3. claimusers doesn't need to be declared public, and you're not declaring the type. So that won't compile either. You did that several times.

**Comment by CubeFromSpace** [comment]
I think explodi is working on clans...

**Comment by CubeFromSpace** [comment]
@explodi Clans are basically complete.

**Comment by CubeFromSpace** [comment]
No offense @lunears

**Comment by lunears** [comment]
None taken!

**Pull request closed without merging**
