### PR TITLE
Fix abandon land with permissions still set

### PR DESCRIPTION
**Pull request by AltQuest**
1) add this in commands: 

https://github.com/AltQuest/bitquest/blob/master/src/main/java/com/bitquest/bitquest/commands/FixAbandonLand.java

2) add this around line 219 on bitquest.java:

        modCommands.put("fixabandonland", new FixAbandonLand());

3) add to plugin.yml

  fixabandonland:
    description: "fixes chunks with no owners that still have permissions"
    usage: "/fixabandonland"

### CODE REVIEW

**Comment by theraccoonbear** [comment]
I'm kind of curious, both because I've never fiddled with REDIS apart from BitQuest, and because I haven't run the code locally in months, but I was looking at the permission fix command [here](https://github.com/AltQuest/bitquest/blob/master/src/main/java/com/bitquest/bitquest/commands/FixAbandonLand.java#L15) and was wondering how that performs.  Reading [this slide deck](https://www.slideshare.net/dvirsky/introduction-to-redis-version-2) they claim just south of 200,000 gets/second (does that sound accurate?).  That's on a 2.2Ghz i7, so I'm not sure how that would work in a more serious production setting, but hopefully that's a rough sense of it.  If that's accurate, this is doing 75,000 x 75,000 gets, or 5,625,000,000 (~5.5 billion).  At 200K/s, that'd be 5,625,000,000 / 200,000 or 28,125 seconds or just under 8 hours.  Does this actually take that long to run?  I'd almost think the number of "misses" (where `BitQuest.REDIS.get("chunk" + x + "," + z + "owner") == null` is true) is so high that'd be more efficient to just enumerate all of the defined keys and then iterate over those, checking as needed.  Like I said, I'm not a REDIS guy at all, but curious if that's doable and might be a more performant tack to take.

**Comment by theraccoonbear** [comment]
Looks like you can enumerate the keys, and the `pattern` parameter should even let you filter down like...

```
 Set<String> ownerKeys = BitQuest.REDIS.keys("chunk*permissions");
```
Then you know all of the plots with permissions and can iterate over those and do the ownership look ups.  If BitQuest has 100,000 players who each own 5 plots on average (and I suspect those guesses are exaggerated) that'd be 500,000 lookups which should be about 10,000x faster.

https://github.com/xetorthio/jedis/blob/master/src/main/java/redis/clients/jedis/Jedis.java#L274
https://redis.io/commands/keys

**Comment by theraccoonbear** [comment]
Totally untested, but something like this https://pastebin.com/7xR6SPZj

**Comment by rmujica** [comment]
@theraccoonbear 
quote from the REDIS docs:

> Warning: consider KEYS as a command that should only be used in production environments with extreme care. It may ruin performance when it is executed against large databases. This command is intended for debugging and special operations, such as changing your keyspace layout. Don't use KEYS in your regular application code. If you're looking for a way to find keys in a subset of your keyspace, consider using SCAN or sets.

**Comment by AltQuest** [comment]
Yeah... I actually dont like using the keys function.. I usually try to do get, set, del, etc whenever I can.

**Comment by juanj** [comment]
Yeah. That fix is terrible inefficient. Maybe this weekend I can implement a fix. Is that ok or you want to implement it @AltQuest ?

You can see an example of how to filter the keys on REDIS in the `migrateClansCommand` 
https://github.com/bitquest/bitquest/blob/master/src/main/java/com/bitquest/bitquest/commands/MigrateClansCommand.java

**Comment by AltQuest** [comment]
idk. Tested by recreating the issue locally. would seem to work 100% you can run just /fixabandonland to see list of info, then run /fixabandonland <true|yes> to remove what it stated before would be removed.

https://github.com/AltQuest/bitquest/blob/master/src/main/java/com/bitquest/bitquest/commands/FixAbandonLand.java

package com.bitquest.bitquest.commands;

import com.bitquest.bitquest.BitQuest;
import org.bukkit.ChatColor;
import org.bukkit.command.Command;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import redis.clients.jedis.ScanParams;
import redis.clients.jedis.ScanResult;

import java.util.Set;
//created by @BitcoinJake09 5/14/18 THIS IS TESTED!!!! and seems to be correct!! i added an extra feature also, you can now just run /fixabandonland to see list of land with owners and permissions in redis and what would be removed. then can also run as /fixabandonland <true|yes>
public class FixAbandonLand extends CommandAction {
    public boolean run(CommandSender sender, Command cmd, String label, String[] args, Player player) {
	int XYsSize=0;
	Set<String> ownerList= BitQuest.REDIS.keys("chunk*owner");
	Set<String> permissionsList = BitQuest.REDIS.keys("*permissions");
	String[] XYs = new String[ownerList.size()];
	String[] subPerms = new String[permissionsList.size()];				
	for(String tempOwnerList:ownerList) {
	XYs[XYsSize]=tempOwnerList.substring(0, tempOwnerList.length() -5);	
	sender.sendMessage(ChatColor.RED+BitQuest.REDIS.get(XYs[XYsSize]+"name")+" is owned by: "+(BitQuest.REDIS.get(tempOwnerList)));
	XYsSize++;
        }

	XYsSize=0;

	for(String tempPermissionsList:permissionsList) {
	subPerms[XYsSize]=tempPermissionsList.substring(0, tempPermissionsList.length() -11);
        sender.sendMessage(ChatColor.YELLOW+tempPermissionsList+" is set to: "+(BitQuest.REDIS.get(subPerms[XYsSize]+"permissions")));
	XYsSize++;
        }
	
	for(int i=0;i<=permissionsList.size()-1;i++) {
		if ((BitQuest.REDIS.get(subPerms[i]+"owner"))==null) {
		sender.sendMessage(ChatColor.GREEN+"To Be Removed: "+subPerms[i] + "permissions is set to: "+BitQuest.REDIS.get(subPerms[i] + "permissions"));
		}
	}
	if((args[0].equalsIgnoreCase("true"))||(args[0].equalsIgnoreCase("yes"))) {
	for(int i=0;i<=permissionsList.size()-1;i++) {
		if ((BitQuest.REDIS.get(subPerms[i]+"owner"))==null) {
			BitQuest.REDIS.del(subPerms[i] + "permissions");
		sender.sendMessage(ChatColor.GREEN+"Removed: "+subPerms[i] + "permissions");
		}
	}
	}
	
         sender.sendMessage(ChatColor.GREEN + "finished");
         return true;
      
    }
}

**Comment by explodi** [comment]
This will be merged manually

**Pull request closed without merging**
