### PR TITLE
Add command to killAllHippies

### PR DESCRIPTION
**Pull request by juanj**
Add a command to call the function "killAllHippies"

### CODE REVIEW

**Comment by Xeyler** [comment]
killAllHippies???

**Comment by juanj** [comment]
The function is called like that...

**Comment by Xeyler** [comment]
Hmm... well, ok, but shouldn't this command be added to the plugin.yml file too?

**Comment by juanj** [comment]
There is any way to create aliases? Or I have to write the code for that too?

**Comment by theraccoonbear** [comment]
I think this would be best if it also gave the mod using it some villager spawn eggs too, so they can then repopulate.

**Comment by juanj** [comment]
Well, seeing how fast they appear I don't think that's a problem.

**Comment by Xeyler** [comment]
The cleanest way we can handle this is by fixing the spawn code. Perhaps we should even consider moving the market away from the villagers. Perhaps it should be a part of the compass instead?

**Comment by theraccoonbear** [comment]
@Xeyler personally, I like the idea of villagers as the place to purchase and needing you to go to them.  Also, if it was compass-based, wouldn't you be able to buy things literally wherever you are?  That seems like a big change.  @juanj you're right they probably will naturally repopulate with the abiogenesis spawn code but @Xeyler is also right that making sure there's no unchecked spawning is really the answer.  I think we should block any breeding between existing villagers so the only time new villagers enter the game is either when the BQ code creates one, or a new chunk with a village is generated.

**Pull request merged**
