### PR TITLE
More stuff

### PR DESCRIPTION
**Pull request by CubeFromSpace**
People wanted stuff.
Mostly suggested on slack

### CODE REVIEW

**Comment by theraccoonbear** [comment]
I don't know if @explodi or anyone else has weighed in, but I would be opposed to allowing people to buy XP.

**Comment by CubeFromSpace** [comment]
On slack, it was suggested, because of mending.

**Comment by theraccoonbear** [comment]
I'm still opposed.  Doesn't mean we can't do it, just sharing my thoughts.

**Comment by CubeFromSpace** [comment]
Ok, that's fine, I'm still taking suggestions on slack.

**Comment by explodi** [comment]
I do agree with @theraccoonbear on XP buys. If possible, donations should come from cosmetic stuff. What do you guys think about pets?

**Comment by theraccoonbear** [comment]
Pets how?  Like, buy a tamed wolf or ocelot?  That'd be cool, I've never actually found an ocelot in BQ.  I'd pay for one.

**Comment by CubeFromSpace** [comment]
I would too

**Comment by CubeFromSpace** [comment]
@explodi, would you like me to remove XP bottles?

**Pull request merged**
