### PR TITLE
Little code improvment

### PR DESCRIPTION
**Pull request by Jorropo**
Code formating,
Code tweaking,
Code CRLF fixing.

### CODE REVIEW

**Comment by Jorropo** [comment]
I don't have finish to recolor all java file (near to end but not yet) (I must do all event file and User.java, Wallet.java, Trade.java (if someone would do it (It is not very funny ^^)))
Here is the color table : (Comment wanted)
GREEN : Worked, YELLOW : Processing, LIGHT_PURPLE : Any money balance, BLUE : Player name, DARK_BLUE UNDERLINE : Link, RED : Server error, DARK_RED : User error, GRAY : Info, DARK_GRAY : Clan, DARK_GREEN : Landname
(Color table are here for simplify reading of what the plugin tells you and for have lot of information and allways formated the same way).

**Comment by Jorropo** [comment]
I finish code recoloring.

**Comment by Jorropo** [comment]
With maven this is  (9.6*faster compilation, 2.2*smaller source size) (This is for travis), on my computer, 10 sec for maven, 2 min 30 for gradlew.

**Comment by explodi** [comment]
merged manually

**Pull request merged**
