### PR TITLE
Buff loot

### PR DESCRIPTION
**Pull request by TheFirstSpirit**
The new loot system is an EXTREME nerf from the last one.

### CODE REVIEW

**Comment by theraccoonbear** [comment]
a 10x increase in potential loot and a 2x increase in likelihood of loot award!?  This seems more like someone wants loot than has thought through where said loot is coming from.  Personally, I would not merge this.

**Comment by TheFirstSpirit** [comment]
okay maybe I might do x5 chance and no buff in amount???

**Comment by syrianrue** [comment]
all you really need on this server is 200 to protect your stuff. everything else, other than end stuff, you can get on your own. cut the loot by 10x.

**Comment by TheFirstSpirit** [comment]
yeahhhh that's what I wanted in the first place...

**Comment by syrianrue** [comment]
i thought you wanted more loot? i just suggested less loot.

**Comment by theraccoonbear** [comment]
@TheFirstSpirit I think the solution to getting more loot is to play more and kill more MOBs, not modify the code to give you more loot.

**Comment by CubeFromSpace** [comment]
@TheFirstSpirit you've been on for a week or two. Most of us have been on for many months or years. You're being greedy. @explodi it's your opinion. Let explodi control loot.

**Comment by explodi** [comment]
I would consider merging this when loot accumulation rate is higher than drop rate; However this is not the case and loot wallet is depleted most days. We should aim neither for empty loot wallets or big accumulation of prizes but a steady redistribution of money spent by players which is the objective of this project.

**Pull request closed without merging**
