### PR TITLE
Fix nether warts

### PR DESCRIPTION
**Pull request by juanj**

### CODE REVIEW

**Comment by Xeyler** [comment]
Is NETHER_STALK equivalent to NETHER_WARTS

**Comment by DabTime** [comment]
The screenshot he posted on my pull request looks like it 
1fdd0ca6-2f7e-11e7-94e2-a9690ec193eb

**Comment by Shiny-andKittens** [comment]
@DabTime there is always a slot missing there

**Comment by DabTime** [comment]
sorry, the photo shows juanj's test.. the left arrow is nether_warts. the right arrow is nether_stalk.

**Comment by Shiny-andKittens** [comment]
Ok, also, the same thing happened when I tried a Wither skull

**Comment by DabTime** [comment]
We need to merge this asap, due to compile error @Xeyler

**Pull request merged**
