### PR TITLE
Report command

### PR DESCRIPTION
**Pull request by juanj**
This command send a message to slack.
#42 

Note. Right now, this breaks the /reload command.

### CODE REVIEW

**Comment by CubeFromSpace** [comment]
Do you know what breaks reload?

**Comment by juanj** [comment]
This is working with web sockets. It seems that when the reload command reloads the plugins, somehow the web sockets remain open and crash the server.

**Comment by CubeFromSpace** [comment]
Maybe close the web sockets when the /reload command is used.

**Comment by juanj** [comment]
I was looking to do that but don't find a way to run the code just before the /reload is executed.

**Comment by CubeFromSpace** [comment]
Maybe ask @explodi

**Pull request merged**
